MGMT-13001: Adding cost by machine type metric
openshift-assisted/prow-jobs-scraper pull request #142
Opened 2023-03-27 13:51 UTC by danmanor

Adding cost by machine type to `equinix` section in the report

2023-03-27 13:51 UTC, danmanor commented
/hold

2023-03-28 08:06 UTC, danmanor commented
/cc @adriengentil

2023-03-29 09:05 UTC, adriengentil requested changes

2023-03-29 09:05 UTC, adriengentil commented on src/jobsautoreport/models.py
> +    S3_XLARGE_X86 = "s3.xlarge.x86"
machine type shouldn't be hardcoded as we change them (and equinix change them) quite often

2023-03-29 09:05 UTC, adriengentil commented on src/jobsautoreport/report.py
> +    m3_small_x86: float = 0
```
>>> m3_small_x86: float = 0
>>> type(m3_small_x86)
<class 'int'>
```
The type annotation in python is not evaluated by the interpreter, the value should be of explicitly of type float

2023-04-27 11:27 UTC, danmanor commented
/cc @osherdp

2023-04-27 11:27 UTC, danmanor commented
/uncc @gamli75 @eliorerz

2023-04-27 13:05 UTC, osherdp commented
a bit busy, uncc-ing for now sorry about it
/uncc

2023-04-27 13:32 UTC, danmanor commented
/cc @rccrdpccl

2023-04-27 13:52 UTC, rccrdpccl commented
/lgtm
although I miss a ton of context :)

2023-04-27 13:59 UTC, danmanor commented
/unhold

2023-04-27 14:08 UTC, danmanor commented
/approve

2023-04-30 08:18 UTC, eliorerz commented
/approve

2023-04-30 08:19 UTC, eliorerz approved these changes

2023-04-30 08:35 UTC, merged