MGMT-13001: Adjusting collection of bandwidth usages
openshift-assisted/prow-jobs-scraper pull request #165
Opened 2023-04-23 11:16 UTC by danmanor

As part of the effort to collect usages correctly, we want to add bandwidth exceed usages to elastic only when their matching regular usage is in the collection interval.

2023-04-23 11:16 UTC, danmanor commented
/uncc @eliorerz  @gamli75

2023-04-23 11:16 UTC, danmanor commented
/cc @osherdp @adriengentil

2023-04-24 07:21 UTC, osherdp requested changes

2023-04-24 07:26 UTC, danmanor commented on src/prowjobsscraper/scraper.py
> +                self._find_not_bandwidth_usage(usage.name, usages)
That is a mistake thanks, whether a usage is `Bandwidth` or not is determined by its plan not its name

2023-04-24 14:39 UTC, merged