MGMT-12553: fixing some typos, changing the cronjob schedule back to 'weekly', formatting the average job duration to be composed of minutes, seconds
openshift-assisted/prow-jobs-scraper pull request #46
Opened 2022-11-22 10:58 UTC by danmanor

1. fixing typos.
2. changing the `cronjob` schedule back to @weekly
3. formatting job average duration to be composed of minutes and seconds

2022-11-22 11:06 UTC, adriengentil commented on src/jobsautoreport/report.py
> +    ) -> tuple[int, int]:
Return a  `timedelta` instead in will allow you to extract the information you need https://docs.python.org/3/library/datetime.html#datetime.timedelta

2022-11-22 16:27 UTC, adriengentil commented on src/jobsautoreport/main.py
> +                    "text": f"• Jobs success rate: _{success_rate}_\n• Number of jobs triggered: _{number_of_jobs_triggered}_\n• Jobs average duration: _{average_jobs_duration.seconds // 60}_ minutes
```suggestion
                    "text": f"• Jobs success rate: _{success_rate}_\n• Number of jobs triggered: _{number_of_jobs_triggered}_\n• Jobs average duration: _{average_jobs_duration.total_seconds() // 60}_ minutes, and _{average_jobs_duration.total_seconds() % 60}_ seconds",
```
`seconds` counts up to one day https://stackoverflow.com/a/51653034

2022-11-22 16:32 UTC, adriengentil commented on src/jobsautoreport/report.py
> +    ) -> timedelta:
```suggestion
    ) -> Optional[timedelta]:
```

2022-11-22 16:32 UTC, adriengentil commented on src/jobsautoreport/report.py
> +            return timedelta(seconds=0)
In order to report the correct information, we need to differentiate a zero from no data.

2022-11-27 13:19 UTC, osherdp requested changes

2022-11-27 13:19 UTC, osherdp commented on src/jobsautoreport/main.py
> +                    "text": f"• Jobs success rate: _{success_rate}_\n• Number of jobs triggered: _{number_of_jobs_triggered}_\n• Jobs average duration: _{int(average_jobs_duration.total_seconds()) //
this line a big too long to read
can you separate it to multiple lines? (maybe in a similar way to how it displays)

2022-11-29 09:33 UTC, adriengentil commented on src/jobsautoreport/main.py
> +    if average_jobs_duration is None:
it could be better to adapt the message instead and have a log message. Let's fix that later.

2022-11-29 09:34 UTC, adriengentil approved these changes

2022-11-29 09:37 UTC, merged

2022-11-29 09:41 UTC, adriengentil commented on src/jobsautoreport/main.py
> +""",
```suggestion
                    "text": (f"• Jobs success rate: _{success_rate}_\n"
                                  f"• Number of jobs triggered: _{number_of_jobs_triggered}_\n"
                                  f"• Jobs average duration: _{int(average_jobs_duration.total_seconds()) // 60}_ minutes, and _{int(average_jobs_duration.total_seconds())  % 60}_ seconds")
```
I missed that, I would be cleaner to have multiline in this way as it keeps the indented property,

2022-11-29 09:42 UTC, adriengentil commented on src/jobsautoreport/main.py
> +""",
the suggestion is bad because I cannot indent properly in the comment field :-(